#FUNCTION TO SYSTEMATIZE and CORRECT COUNTRY NAMES
country_cleaner <- function(DATAFILE) {
  
  
  # DATAFILE<-ALLDATA
  # SOME NOTES:
  
  # DATAFILE$COUNTRY<-as.factor(DATAFILE$COUNTRY)
  # levels(DATAFILE$COUNTRY)
  DATAFILE$COUNTRY<-as.character(DATAFILE$COUNTRY)
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="Australiatralia"]<-"Australia"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="ITALY"]<-"Italy"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="P. R. China"]<-"China"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="MEXICO"]<-"Mexico"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="NewZealand"]<-"New Zealand"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="N. Ireland"]<-"Northern Ireland"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="PuertoRico"]<-"Puerto Rico"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="The Netherlands"]<-"Netherlands"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="UK"]<-"United Kingdom"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="US"]<-"USA"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="Usa"]<-"USA"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="UsA"]<-"USA"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="United States"]<-"USA"
  DATAFILE$COUNTRY[DATAFILE$COUNTRY=="missing"]<-NA
  DATAFILE$COUNTRY<-gsub("IRAN", "Iran", DATAFILE$COUNTRY)
  DATAFILE$COUNTRY<-gsub("California", "USA", DATAFILE$COUNTRY)
  DATAFILE$COUNTRY<-gsub("Germanny", "Germany", DATAFILE$COUNTRY)
  DATAFILE$COUNTRY<-gsub("P.R. China", "China", DATAFILE$COUNTRY)
  
  
  return(DATAFILE)
  
}