#FUNCTION TO CLEAN AND PROCESS EVOL
clean_EVOL <- function(DATAFILE) {
  
  DATAFILE$COUNTRY<-as.character(DATAFILE$COUNTRY)
  DATAFILE$STATE<-as.character(DATAFILE$STATE)
  DATAFILE$COUNTRY[DATAFILE$LAST_NAME=="Knowlton" & DATAFILE$FIRST_NAME=="Nancy"]<-"Panama"
  DATAFILE$STATE[DATAFILE$LAST_NAME=="Knowlton" & DATAFILE$FIRST_NAME=="Nancy"]<-NA
  DATAFILE<-DATAFILE %>% rename("TITLE"="TITLE.x")
  head(DATAFILE,10)

  return(DATAFILE)
}


